/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "on-error": "#490006",
          "secondary-fixed": "#ccdff6",
          "surface-container-low": "#0e141a",
          "tertiary-fixed": "#00d9fe",
          "surface-container-highest": "#1f262f",
          "error-dim": "#d7383b",
          "surface-container-lowest": "#000000",
          "surface-container": "#141a21",
          "tertiary": "#77e3ff",
          "on-secondary": "#3e5063",
          "on-primary-fixed-variant": "#006d4e",
          "on-tertiary-fixed": "#00313b",
          "on-tertiary-fixed-variant": "#005160",
          "on-background": "#f0f4fc",
          "primary-dim": "#7eefc0",
          "secondary-fixed-dim": "#bed1e7",
          "primary-container": "#3eb489",
          "on-surface-variant": "#a7abb3",
          "tertiary-dim": "#00caec",
          "surface-variant": "#1f262f",
          "on-tertiary": "#005160",
          "on-error-container": "#ffa8a3",
          "surface-bright": "#252d36",
          "primary": "#8cfece",
          "secondary-dim": "#bed1e7",
          "inverse-primary": "#006d4e",
          "on-secondary-fixed-variant": "#485a6d",
          "on-primary-fixed": "#004d36",
          "primary-fixed-dim": "#7eefc0",
          "on-secondary-fixed": "#2b3d4f",
          "error": "#ff716c",
          "background": "#0a0f14",
          "tertiary-fixed-dim": "#00caec",
          "surface": "#0a0f14",
          "inverse-on-surface": "#50555d",
          "primary-fixed": "#8cfece",
          "on-primary-container": "#00291b",
          "error-container": "#9f0519",
          "surface-dim": "#0a0f14",
          "on-secondary-container": "#bfd2e9",
          "on-tertiary-container": "#004754",
          "inverse-surface": "#f8f9ff",
          "surface-tint": "#8cfece",
          "outline": "#71767d",
          "outline-variant": "#43484f",
          "secondary": "#ccdff6",
          "on-surface": "#f0f4fc",
          "surface-container-high": "#1a2028",
          "on-primary": "#006145",
          "secondary-container": "#36485b",
          "tertiary-container": "#00d9fe"
        },
        fontFamily: {
          "lexend": ["Lexend", "sans-serif"]
        },
        borderRadius: {
            "DEFAULT": "1rem", 
            "lg": "2rem", 
            "xl": "3rem", 
            "full": "9999px"
        },
      },
    },
    plugins: [],
  }
