import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import YouTubePlayer from "../components/YouTubePlayer";

/**
 * FeedPage
 * Focus mode for watching a specific AI-generated clip.
 */
export default function FeedPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const { video, clip } = location.state || {};
  const [isMuted, setIsMuted] = useState(true);

  if (!video || !clip) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center text-white">
        <div className="text-center space-y-4">
          <p className="opacity-60">Clip data not found.</p>
          <button onClick={() => navigate("/")} className="bg-white text-black px-6 py-2 rounded-full font-bold">Go Home</button>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black text-white h-[100dvh] w-full overflow-hidden flex flex-col">
      {/* Top Controls */}
      <div className="absolute top-0 w-full z-50 p-6 flex justify-between items-start pointer-events-none">
        <button 
          onClick={() => navigate(-1)}
          className="w-12 h-12 rounded-full bg-black/40 backdrop-blur-xl flex items-center justify-center pointer-events-auto active:scale-90 transition-transform"
        >
          <span className="material-symbols-outlined">arrow_back</span>
        </button>
        
        <div className="text-right pointer-events-auto">
          <button 
            onClick={() => setIsMuted(!isMuted)}
            className="w-12 h-12 rounded-full bg-black/40 backdrop-blur-xl flex items-center justify-center active:scale-90 transition-transform"
          >
            <span className="material-symbols-outlined">{isMuted ? "volume_off" : "volume_up"}</span>
          </button>
        </div>
      </div>

      {/* Main Player Area */}
      <main className="flex-1 relative flex items-center justify-center">
        <YouTubePlayer 
          videoId={video.id} 
          start={clip.start} 
          end={clip.end} 
          isMuted={isMuted}
          onReady={(e) => {
            // Internal sync is now handled by YouTubePlayer props
          }}
        />

        {/* Overlaying Info (Bottom) */}
        <div className="absolute bottom-0 w-full bg-gradient-to-t from-black via-black/60 to-transparent p-8 pt-20">
          <div className="max-w-md mx-auto space-y-4">
            <div className="flex items-center gap-2">
              <span className="bg-emerald-500 text-black text-[10px] font-black px-2 py-0.5 rounded tracking-widest uppercase">
                Focus Clip
              </span>
              <span className="text-white/40 text-xs font-medium">✨ Generated by Gemini</span>
            </div>
            
            <h2 className="text-2xl font-bold tracking-tight leading-tight">
              {clip.title}
            </h2>
            
            <p className="text-white/70 text-sm leading-relaxed line-clamp-3">
              {clip.summary}
            </p>

            <div className="pt-4 flex items-center gap-4">
              <div className="flex-1 h-1 bg-white/20 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: "0%" }}
                  animate={{ width: "100%" }}
                  transition={{ duration: clip.end - clip.start, repeat: Infinity, ease: "linear" }}
                  className="h-full bg-emerald-400 shadow-[0_0_10px_#4ade80]"
                />
              </div>
              <span className="text-[10px] font-mono text-white/40">{clip.duration}</span>
            </div>
          </div>
        </div>
      </main>

      {/* Unmute Tap Target (if muted) */}
      <AnimatePresence>
        {isMuted && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setIsMuted(false)}
            className="absolute inset-0 z-40 flex items-center justify-center bg-black/20 cursor-pointer"
          >
            <div className="bg-white/10 backdrop-blur-xl px-6 py-3 rounded-full flex items-center gap-3 border border-white/10">
              <span className="material-symbols-outlined text-emerald-400">volume_up</span>
              <span className="text-sm font-bold tracking-tight">Tap to Unmute</span>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
